[sky_emission]
# Each sky emission has a weighting factor between 0 and 1

# Synchrotron, Dust, Free-free, AME
# Websky CIB, tSZ, kSZ
foreground_emission = 1

# Planck cosmological parameters, no tensor modes
CMB_unlensed = 1

# CMB lensed - CMB unlensed:
# 1 for lensed CMB
# 0 for unlensed CMB
# >0, <1 for residual after de-lensing
CMB_lensing_signal = 1

CMB_tensor_to_scalar_ratio = 0.005

[experiment]

total_experiment_length_years = 7


# Number of splits, 1 generates only full mission
# 2-7 generates the full mission map and then the requested number
# of splits scaled accordingly. E.g. 7 generates the full mission
# map and 7 equal (yearly) maps
number_of_splits = 1

include_atmosphere = false

# atmosphere maps scaling factors (multipled to input maps)
atmosphere_scaling_T = 1.0
atmosphere_scaling_P = 1.0

include_noise = false

# between 0 and 1, typically 0.2
observing_efficiency.default = 0.2

# we can override the observing efficiency for specific sites/bands
# always specify first site, then telescope, then band
observing_efficiency.Pole.SAT.HFS = 0.2
observing_efficiency.Pole.LAT.HFL = 0.2

# we can also specify defaults for sites (notice capitalization) or telescopes
observing_efficiency.Pole.SAT.default = 0.2
observing_efficiency.Chile.default = 0.2


[telescopes]

    # Telescope names are not used within the software

    [telescopes.SAT]
    # Tubes for each SAT should be 3

    SAT1 = { LFS=0, MFLS= 3, MFHS=0, HFS=0, site="Pole", years=7 }
    SAT3 = { LFS=0, MFLS= 0, MFHS=3, HFS=0, site="Pole", years=7 }
    SAT5 = { LFS=1, MFLS= 0, MFHS=0, HFS=2, site="Pole", years=7 }

    SAT0 = { LFS=0, MFLS= 3, MFHS=0, HFS=0, site="Pole", years=7 }
    SAT2 = { LFS=0, MFLS= 0, MFHS=3, HFS=0, site="Pole", years=7 }
    SAT4 = { LFS=1, MFLS= 0, MFHS=0, HFS=2, site="Pole", years=7 }

    [telescopes.LAT]
    # Tubes for each LAT should be 19

    # Legacy survey LAT deployed in Chile

    LAT0 = { ULFL=0, LFL= 2, MFL=12, HFL=5, site="Chile", years=7 }
    LAT1 = { ULFL=0, LFL= 2, MFL=12, HFL=5, site="Chile", years=7 }

    # Delensing survey LAT deployed at Pole

    LAT2 = { ULFPL=1, LFPL= 2, MFPL=11, HFPL=4, site="Pole", years=7 }
